owner: eskogh
repo: upptime

sites:
  - name: x86.se
    url: https://x86.se
  - name: resume.skogh.org
    url: https://resume.skogh.org/upptime-health
    method: GET
    maxResponseTime: 4000
    expectedStatusCodes:
      - 200
  - name: Shinobi NVR
    url: https://nvr.x86.se
  - name: upload.linux.army
    url: https://upload.linux.army
  - name: Homeassistant
    url: https://homeassistant.senate.sx:8123

status-website:
  themeUrl: "https://status.x86.se/web3-clean.css"
  cname: status.x86.se
  name: "x86 Status"
  logoUrl: "https://x86.se/wp-content/uploads/2025/09/x86_white-1.png"
  introTitle: "**x86 Status** — transparent uptime with a Web3 coat of paint"
  introMessage: >
    Live health checks for our sites and APIs, updated automatically every 5 minutes.
    Built with [Upptime](https://github.com/upptime/upptime) and hosted on GitHub Pages.
    Green means fast and healthy; yellow is degraded; red indicates an incident.
